### ISSUE TITLE
Update Homebrew Cask URL

### ISSUE THREAD

**Issue by reitermarkus** [grettke/osx-provision#1]
Hi, we just wanted to let you know that you are still linking to the old Homebrew Cask homepage (`caskroom.io`) in [`provisioning.org`](https://github.com/grettke/osx-provision/blob/0dd95280343b98f85a0223909d633e3321a2fa27/Sierra/provisioning.org). This domain expired a few years ago and is not controlled by Homebrew anymore.

When you get a chance, please update the link to https://brew.sh/ or https://formulae.brew.sh/cask/.

Thank you,
the Homebrew team.

**Comment by grettke** [comment]
@reitermarkus Thank you.
